export const countries = [
  {
    code: "BR",
    name: "Brasil",
    dialCode: "+55",
    flag: "🇧🇷",
    format: "(##) #####-####",
    maxLength: 11,
  },
  {
    code: "US",
    name: "Estados Unidos",
    dialCode: "+1",
    flag: "🇺🇸",
    format: "(###) ###-####",
    maxLength: 10,
  },
  {
    code: "PT",
    name: "Portugal",
    dialCode: "+351",
    flag: "🇵🇹",
    format: "### ### ###",
    maxLength: 9,
  },
  {
    code: "AR",
    name: "Argentina",
    dialCode: "+54",
    flag: "🇦🇷",
    format: "## ####-####",
    maxLength: 10,
  },
  {
    code: "MX",
    name: "México",
    dialCode: "+52",
    flag: "🇲🇽",
    format: "## #### ####",
    maxLength: 10,
  },
  {
    code: "ES",
    name: "Espanha",
    dialCode: "+34",
    flag: "🇪🇸",
    format: "### ## ## ##",
    maxLength: 9,
  },
  {
    code: "FR",
    name: "França",
    dialCode: "+33",
    flag: "🇫🇷",
    format: "# ## ## ## ##",
    maxLength: 9,
  },
  {
    code: "DE",
    name: "Alemanha",
    dialCode: "+49",
    flag: "🇩🇪",
    format: "### #######",
    maxLength: 11,
  },
  {
    code: "IT",
    name: "Itália",
    dialCode: "+39",
    flag: "🇮🇹",
    format: "### ### ####",
    maxLength: 10,
  },
  {
    code: "GB",
    name: "Reino Unido",
    dialCode: "+44",
    flag: "🇬🇧",
    format: "#### ######",
    maxLength: 10,
  },
  {
    code: "CA",
    name: "Canadá",
    dialCode: "+1",
    flag: "🇨🇦",
    format: "(###) ###-####",
    maxLength: 10,
  },
  {
    code: "AU",
    name: "Austrália",
    dialCode: "+61",
    flag: "🇦🇺",
    format: "### ### ###",
    maxLength: 9,
  },
  {
    code: "JP",
    name: "Japão",
    dialCode: "+81",
    flag: "🇯🇵",
    format: "##-####-####",
    maxLength: 10,
  },
  {
    code: "CN",
    name: "China",
    dialCode: "+86",
    flag: "🇨🇳",
    format: "### #### ####",
    maxLength: 11,
  },
  {
    code: "IN",
    name: "Índia",
    dialCode: "+91",
    flag: "🇮🇳",
    format: "##### #####",
    maxLength: 10,
  },
  {
    code: "RU",
    name: "Rússia",
    dialCode: "+7",
    flag: "🇷🇺",
    format: "(###) ###-##-##",
    maxLength: 10,
  },
  {
    code: "KR",
    name: "Coreia do Sul",
    dialCode: "+82",
    flag: "🇰🇷",
    format: "##-####-####",
    maxLength: 10,
  },
  {
    code: "CL",
    name: "Chile",
    dialCode: "+56",
    flag: "🇨🇱",
    format: "# #### ####",
    maxLength: 9,
  },
  {
    code: "CO",
    name: "Colômbia",
    dialCode: "+57",
    flag: "🇨🇴",
    format: "### ### ####",
    maxLength: 10,
  },
  {
    code: "PE",
    name: "Peru",
    dialCode: "+51",
    flag: "🇵🇪",
    format: "### ### ###",
    maxLength: 9,
  },
  {
    code: "VE",
    name: "Venezuela",
    dialCode: "+58",
    flag: "🇻🇪",
    format: "###-###-####",
    maxLength: 10,
  },
  {
    code: "UY",
    name: "Uruguai",
    dialCode: "+598",
    flag: "🇺🇾",
    format: "## ### ###",
    maxLength: 8,
  },
  {
    code: "PY",
    name: "Paraguai",
    dialCode: "+595",
    flag: "🇵🇾",
    format: "### ### ###",
    maxLength: 9,
  },
  {
    code: "EC",
    name: "Equador",
    dialCode: "+593",
    flag: "🇪🇨",
    format: "## ### ####",
    maxLength: 9,
  },
  {
    code: "BO",
    name: "Bolívia",
    dialCode: "+591",
    flag: "🇧🇴",
    format: "# ### ####",
    maxLength: 8,
  },
  {
    code: "NL",
    name: "Países Baixos",
    dialCode: "+31",
    flag: "🇳🇱",
    format: "# ## ## ## ##",
    maxLength: 9,
  },
  {
    code: "BE",
    name: "Bélgica",
    dialCode: "+32",
    flag: "🇧🇪",
    format: "### ## ## ##",
    maxLength: 9,
  },
  {
    code: "CH",
    name: "Suíça",
    dialCode: "+41",
    flag: "🇨🇭",
    format: "## ### ## ##",
    maxLength: 9,
  },
  {
    code: "AT",
    name: "Áustria",
    dialCode: "+43",
    flag: "🇦🇹",
    format: "### ### ####",
    maxLength: 10,
  },
  {
    code: "PL",
    name: "Polônia",
    dialCode: "+48",
    flag: "🇵🇱",
    format: "### ### ###",
    maxLength: 9,
  },
  {
    code: "SE",
    name: "Suécia",
    dialCode: "+46",
    flag: "🇸🇪",
    format: "##-### ## ##",
    maxLength: 9,
  },
  {
    code: "NO",
    name: "Noruega",
    dialCode: "+47",
    flag: "🇳🇴",
    format: "### ## ###",
    maxLength: 8,
  },
  {
    code: "DK",
    name: "Dinamarca",
    dialCode: "+45",
    flag: "🇩🇰",
    format: "## ## ## ##",
    maxLength: 8,
  },
  {
    code: "FI",
    name: "Finlândia",
    dialCode: "+358",
    flag: "🇫🇮",
    format: "## ### ####",
    maxLength: 9,
  },
  {
    code: "IE",
    name: "Irlanda",
    dialCode: "+353",
    flag: "🇮🇪",
    format: "## ### ####",
    maxLength: 9,
  },
  {
    code: "NZ",
    name: "Nova Zelândia",
    dialCode: "+64",
    flag: "🇳🇿",
    format: "## ### ####",
    maxLength: 9,
  },
  {
    code: "ZA",
    name: "África do Sul",
    dialCode: "+27",
    flag: "🇿🇦",
    format: "## ### ####",
    maxLength: 9,
  },
  {
    code: "AE",
    name: "Emirados Árabes",
    dialCode: "+971",
    flag: "🇦🇪",
    format: "## ### ####",
    maxLength: 9,
  },
  {
    code: "SA",
    name: "Arábia Saudita",
    dialCode: "+966",
    flag: "🇸🇦",
    format: "## ### ####",
    maxLength: 9,
  },
  {
    code: "IL",
    name: "Israel",
    dialCode: "+972",
    flag: "🇮🇱",
    format: "##-###-####",
    maxLength: 9,
  },
  {
    code: "TR",
    name: "Turquia",
    dialCode: "+90",
    flag: "🇹🇷",
    format: "### ### ####",
    maxLength: 10,
  },
  {
    code: "GR",
    name: "Grécia",
    dialCode: "+30",
    flag: "🇬🇷",
    format: "### ### ####",
    maxLength: 10,
  },
  {
    code: "CZ",
    name: "República Tcheca",
    dialCode: "+420",
    flag: "🇨🇿",
    format: "### ### ###",
    maxLength: 9,
  },
  {
    code: "HU",
    name: "Hungria",
    dialCode: "+36",
    flag: "🇭🇺",
    format: "## ### ####",
    maxLength: 9,
  },
  {
    code: "RO",
    name: "Romênia",
    dialCode: "+40",
    flag: "🇷🇴",
    format: "### ### ###",
    maxLength: 9,
  },
  {
    code: "UA",
    name: "Ucrânia",
    dialCode: "+380",
    flag: "🇺🇦",
    format: "## ### ####",
    maxLength: 9,
  },
  {
    code: "TH",
    name: "Tailândia",
    dialCode: "+66",
    flag: "🇹🇭",
    format: "## ### ####",
    maxLength: 9,
  },
  {
    code: "SG",
    name: "Singapura",
    dialCode: "+65",
    flag: "🇸🇬",
    format: "#### ####",
    maxLength: 8,
  },
  {
    code: "MY",
    name: "Malásia",
    dialCode: "+60",
    flag: "🇲🇾",
    format: "##-### ####",
    maxLength: 9,
  },
  {
    code: "ID",
    name: "Indonésia",
    dialCode: "+62",
    flag: "🇮🇩",
    format: "### ### ####",
    maxLength: 10,
  },
  {
    code: "PH",
    name: "Filipinas",
    dialCode: "+63",
    flag: "🇵🇭",
    format: "### ### ####",
    maxLength: 10,
  },
  {
    code: "VN",
    name: "Vietnã",
    dialCode: "+84",
    flag: "🇻🇳",
    format: "### ### ###",
    maxLength: 9,
  },
  {
    code: "EG",
    name: "Egito",
    dialCode: "+20",
    flag: "🇪🇬",
    format: "### ### ####",
    maxLength: 10,
  },
  {
    code: "NG",
    name: "Nigéria",
    dialCode: "+234",
    flag: "🇳🇬",
    format: "### ### ####",
    maxLength: 10,
  },
  {
    code: "KE",
    name: "Quênia",
    dialCode: "+254",
    flag: "🇰🇪",
    format: "### ### ###",
    maxLength: 9,
  },
  {
    code: "MA",
    name: "Marrocos",
    dialCode: "+212",
    flag: "🇲🇦",
    format: "## ### ####",
    maxLength: 9,
  },
  {
    code: "AO",
    name: "Angola",
    dialCode: "+244",
    flag: "🇦🇴",
    format: "### ### ###",
    maxLength: 9,
  },
  {
    code: "MZ",
    name: "Moçambique",
    dialCode: "+258",
    flag: "🇲🇿",
    format: "## ### ####",
    maxLength: 9,
  },
] as const;

export type Country = (typeof countries)[number];

export interface PhoneInputValue {
  country: Country;
  phoneNumber: string;
  fullNumber: string;
  isValid: boolean;
}

export const localeToCountry: Record<string, string> = {
  "pt-BR": "BR",
  pt: "PT",
  "en-US": "US",
  "en-GB": "GB",
  "en-AU": "AU",
  "en-CA": "CA",
  "en-NZ": "NZ",
  en: "US",
  "es-AR": "AR",
  "es-MX": "MX",
  "es-ES": "ES",
  "es-CL": "CL",
  "es-CO": "CO",
  "es-PE": "PE",
  "es-VE": "VE",
  "es-UY": "UY",
  "es-PY": "PY",
  "es-EC": "EC",
  "es-BO": "BO",
  es: "ES",
  "fr-FR": "FR",
  "fr-CA": "CA",
  "fr-BE": "BE",
  "fr-CH": "CH",
  fr: "FR",
  "de-DE": "DE",
  "de-AT": "AT",
  "de-CH": "CH",
  de: "DE",
  "it-IT": "IT",
  "it-CH": "CH",
  it: "IT",
  "ja-JP": "JP",
  ja: "JP",
  "zh-CN": "CN",
  zh: "CN",
  "ko-KR": "KR",
  ko: "KR",
  "ru-RU": "RU",
  ru: "RU",
  "nl-NL": "NL",
  "nl-BE": "BE",
  nl: "NL",
  "pl-PL": "PL",
  pl: "PL",
  "sv-SE": "SE",
  sv: "SE",
  "no-NO": "NO",
  no: "NO",
  "da-DK": "DK",
  da: "DK",
  "fi-FI": "FI",
  fi: "FI",
  "tr-TR": "TR",
  tr: "TR",
  "ar-SA": "SA",
  "ar-AE": "AE",
  "ar-EG": "EG",
  "ar-MA": "MA",
  ar: "SA",
  "he-IL": "IL",
  he: "IL",
  "th-TH": "TH",
  th: "TH",
  "vi-VN": "VN",
  vi: "VN",
  "id-ID": "ID",
  id: "ID",
  "ms-MY": "MY",
  ms: "MY",
  "uk-UA": "UA",
  uk: "UA",
  "cs-CZ": "CZ",
  cs: "CZ",
  "hu-HU": "HU",
  hu: "HU",
  "ro-RO": "RO",
  ro: "RO",
  "el-GR": "GR",
  el: "GR",
  "hi-IN": "IN",
  hi: "IN",
  "bn-IN": "IN",
};

export function getDefaultCountry(): Country {
  if (typeof window === "undefined") {
    return countries.find((c) => c.code === "BR")!;
  }

  const browserLocale =
    navigator.language ||
    (navigator as { userLanguage?: string }).userLanguage ||
    "en-US";

  let countryCode = localeToCountry[browserLocale];

  if (!countryCode) {
    const languageOnly = browserLocale.split("-")[0];
    countryCode = localeToCountry[languageOnly];
  }

  countryCode = countryCode || "BR";

  return (
    countries.find((c) => c.code === countryCode) ||
    countries.find((c) => c.code === "BR")!
  );
}

export function getCountryByDialCode(dialCode: string): Country | undefined {
  const normalized = dialCode.startsWith("+") ? dialCode : `+${dialCode}`;
  return countries.find((c) => c.dialCode === normalized);
}

export function getCountryByCode(code: string): Country | undefined {
  return countries.find((c) => c.code.toLowerCase() === code.toLowerCase());
}

export function getCountryNameByDialCode(dialCode: string): string {
  const country = getCountryByDialCode(dialCode);
  return country?.name || dialCode;
}
